export const SET_FILES_STATE = "SET_FILES_STATE";
export const SET_PATH_TITLE = "SET_PATH_TITLE";
export const SET_FILES_ARR = "SET_FILES_ARR";
// export const SET_CURRENT_COURSE = "SET_CURRENT_COURSE";